# Generated by Django 3.1.7 on 2021-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(upload_to='myimage'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(upload_to='myimage'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
