# Generated by Django 3.1.7 on 2021-03-18 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0002_auto_20210313_1458'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_address_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlog.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
