# Generated by Django 3.1.7 on 2021-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_address_street_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_mobile',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
