# Generated by Django 3.1.7 on 2021-03-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0002_auto_20210313_1458'),
        ('user', '0007_auto_20210321_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_image1',
            field=models.ImageField(default='image', upload_to='userimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_date', models.DateTimeField(auto_now_add=True)),
                ('wish_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlog.products')),
                ('wish_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetail')),
            ],
        ),
    ]
